version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs"]
  skip_doc_coverage = ["function-declaration", "function-expression", "arrow-function-expression", "class-declaration", "class-expression", "method-definition"]

