version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - PORT=${PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
    volumes:
      - /app/node_modules
      - ./backend/config:/app/config
      - ./backend/src:/app/src
      - ./backend/test:/app/test
    networks:
      - proxy
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    volumes:
      - /app/node_modules
      - ./frontend:/app
    networks:
      - proxy

networks:
  proxy:
    external: true
