-- AlterEnum
ALTER TYPE "ActivityType" ADD VALUE 'TAG_CREATED';
ALTER TYPE "ActivityType" ADD VALUE 'TAG_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE 'TAG_DELETED';
ALTER TYPE "ActivityType" ADD VALUE 'TAG_APPROVED';
ALTER TYPE "ActivityType" ADD VALUE 'TAG_REJECTED';
