-- AlterEnum
ALTER TYPE "AdminActionType" ADD VALUE 'INGREDIENT_APPROVED';
ALTER TYPE "AdminActionType" ADD VALUE 'INGREDIENT_REJECTED';
ALTER TYPE "AdminActionType" ADD VALUE 'UNIT_CREATED';
ALTER TYPE "AdminActionType" ADD VALUE 'UNIT_UPDATED';
ALTER TYPE "AdminActionType" ADD VALUE 'UNIT_DELETED';
